name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Goose
        run: "go install github.com/pressly/goose/v3/cmd/goose@latest"

      - name: Build the binary
        run: scripts/buildprod.sh

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "gcloud builds submit"
        run: "gcloud builds submit --tag asia-northeast1-docker.pkg.dev/notely-433900-i0/notely-ar-repo/notely:stable ."

      - name: Run DB migrations with goose
        run: "goose turso $DATABASE_URL up"

      - name: Deploy to Cloud Run
        run: "gcloud run deploy notely --image asia-northeast1-docker.pkg.dev/notely-433900-i0/notely-ar-repo/notely:stable --region asia-northeast1 --allow-unauthenticated --project notely-433900-i0 --max-instances=4"
