name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Force Failure
        run: go test ./... -cover

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  styles:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Check formatting issues
        run: test -z $(go fmt ./...)

      - name: Linting checks
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
